spring:
  application:
    name: notification-service

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

  data:
    redis:
      host: localhost
      port: 6379




spring.config.import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true