spring:
  application:
    name: api-gateway-server

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"


            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true


      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/**

        - id: livre-service
          uri: lb://livre-service
          predicates:
                - Path=/livre-service/**




        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

        - id: statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=/statistics-service/**


        - id: notification-service
          uri: ws://notification-service
          predicates:
            - Path=/notification-service/**









        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1


  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
