spring:
  application:
    name: api-gateway-server

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true


    gateway:
      routes:
        # Define routes for your services



spring.config.import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
